#!/bin/bash

clear
#Check if it's Apple
if [ -d /usr/local/bin/Bootloader ]; then # if Bootloader folder exist
	echo "FAIL: This is not an Apple."
	echo
	exit 1
fi
#Done Check if it's Apple

if [[ ! `echo $PATH|grep "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"` ]]; then # if Not Found
	export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
fi
export LC_ALL=C
macOS_VERSION=$(sw_vers -productVersion)
macOS_MAJOR=$(echo "${macOS_VERSION}"|awk -F'.' '{print $1}')
macOS_MINOR=$(echo "${macOS_VERSION}"|awk -F'.' '{print $2}')
macOS_PATCH=$(echo "${macOS_VERSION}"|awk -F'.' '{print $3}')
macOS_BUILD="${macOS_MAJOR}.${macOS_MINOR}"
ver () { echo "$@"|awk -F. '{ printf("%d%03d%03d", $1,$2,$3); }'; }
#ver () { echo "$@"|awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; }
BoldON="\033[1m"
BoldOFF="\033[0m"

echo -e "${BoldON}Running macOS Maintenance.${BoldOFF}"
echo

#Enabling Tweaks
if [[ $(id -u) -ne 0 ]]; then # If not Root
	echo "Updating Preferences."
	if [ $(ver "$macOS_BUILD") -ge $(ver 10.7) ]; then # Lion & above
		defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
		defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
		defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true
		defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true
		defaults write com.apple.NetworkBrowser DisableAirDrop -bool false
		defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
		defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
		defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
		defaults write -g com.apple.swipescrolldirection -bool false
		defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true
		defaults write com.apple.dock autohide -bool true
		defaults write com.apple.finder ShowStatusBar -bool true
		defaults write NSGlobalDomain AppleShowScrollBars -string 'Always'
		defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false
		defaults write com.apple.Safari AutoOpenSafeDownloads -bool false
		defaults write com.apple.CrashReporter UseUNC 1
		defaults write com.apple.LaunchServices LSQuarantine -bool false
	fi
	if [ $(ver "$macOS_BUILD") -eq $(ver 10.10) -o $(ver "$macOS_BUILD") -eq $(ver 10.11) -o $(ver "$macOS_BUILD") -eq $(ver 10.12) -o $(ver "$macOS_BUILD") -eq $(ver 10.13) ]; then # Yose-HS
		defaults write NSGlobalDomain AppleICUDateFormatStrings -dict-add "1" "MM/dd/yyyy"
		defaults write NSGlobalDomain AppleICUDateFormatStrings -dict-add "2" "MMM d y"
		defaults write NSGlobalDomain AppleICUDateFormatStrings -dict-add "3" "MMMM d y"
		defaults write NSGlobalDomain AppleICUDateFormatStrings -dict-add "4" "EEEE, MMMM d y"
	fi
	if [ $(ver "$macOS_BUILD") -ge $(ver 10.13) ]; then # HS & above
		defaults write -g CSUIDisable32BitWarning -boolean true
	fi
	if [ $(ver "$macOS_BUILD") -ge $(ver 10.14) ]; then # Mojave & above
		defaults write com.apple.dock show-recents -bool false
	fi
fi
#Done Enabling Tweaks

#Admin Rights
if [ $EUID != 0 ]; then
	sudo "$0" "$@"
	exit $?
fi
#Done Admin Rights

#Disabling Gatekeeper
if [ $(ver "$macOS_BUILD") -le $(ver 10.15) ]; then # Catalina & below
	spctl --master-disable
else
	spctl --global-disable
fi
if [ $(ver "$macOS_BUILD") -ge $(ver 10.10) ]; then # Yose & above
	defaults write /Library/Preferences/com.apple.security GKAutoRearm -bool false
fi
#Done Disabling Gatekeeper

#Hide OTHER account from the Login Window
defaults write /Library/Preferences/com.apple.loginwindow SHOWOTHERUSERS_MANAGED -bool false
#Done Hide OTHER account from the Login Window

rm -Rf /.Trashes/* &>/dev/null
rm -Rf "$HOME"/.Trash/* &>/dev/null
rm -Rf "$HOME"/Trash/* &>/dev/null
rm -Rf /Library/Logs/DiagnosticReports/* &>/dev/null
if [ $(ver "$macOS_BUILD") -eq $(ver 10.6) ]; then # SL
	dscacheutil -flushcache &>/dev/null
else
	dscacheutil -flushcache &>/dev/null
	killall -HUP mDNSResponder &>/dev/null
fi

echo "Done."
echo

exit 0
